###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments?postId=693b2c68048595d9923e7be7

###
POST http://localhost:3000/comments
Content-Type: application/json  

{
  "postId": "693b2c68048595d9923e7be7",
  "text": "nice post",
  "sender": "Amit Miz"
}

###
PUT http://localhost:3000/comments/693b2cad048595d9923e7bf0
Content-Type: application/json  

{
  "text": "WOWWW"
}

###
DELETE http://localhost:3000/comments/693b2cad048595d9923e7bf0
