###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments?postId=692b40571d7126859bf9396b

###
POST http://localhost:3000/comments
Content-Type: application/json  

{
  "postId": "692b40571d7126859bf9396b",
  "text": "nice post",
  "sender": "Amit Miz"
}

###
PUT http://localhost:3000/comments/694c4cd2b3136ace60e149ba
Content-Type: application/json  

{
  "text": "WOWWW"
}

###
DELETE http://localhost:3000/comments/694c4cd2b3136ace60e149ba
