###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/693b2c68048595d9923e7be7

###

GET http://localhost:3000/posts/?sender=Amit

###
POST http://localhost:3000/posts
Content-Type: application/json  

{
  "sender": "Amit",
  "message": "Hi Im Amit BRO"
}

###
PUT http://localhost:3000/posts/693b2c68048595d9923e7be7
Content-Type: application/json  

{
  "message": "hhhhhhhhhhhhhhhhhh"
}