###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/694c4c8db3136ace60e149a9

###

GET http://localhost:3000/posts/?sender=Amit

###
POST http://localhost:3000/posts
Content-Type: application/json  

{
  "sender": "Gali",
  "message": "Hi This is My post"
}

###
PUT http://localhost:3000/posts/693b2c68048595d9923e7be7
Content-Type: application/json  

{
  "message": "hhhhhhhhhhhhhhhhhh"
}